<?php
require("../../inc/header.php");

/*
		SoftName : EmpireBak Version 2010
		Author   : wm_chief
		Copyright: Powered by www.phome.net
*/

DoSetDbChar('utf8');
E_D("DROP TABLE IF EXISTS `hhs_goods`;");
E_C("CREATE TABLE `hhs_goods` (
  `goods_id` mediumint(8) unsigned NOT NULL AUTO_INCREMENT,
  `cat_id` smallint(5) unsigned NOT NULL DEFAULT '0',
  `goods_sn` varchar(60) NOT NULL DEFAULT '',
  `goods_name` varchar(120) NOT NULL DEFAULT '',
  `goods_name_style` varchar(60) NOT NULL DEFAULT '+',
  `click_count` int(10) unsigned NOT NULL DEFAULT '0',
  `brand_id` smallint(5) unsigned NOT NULL DEFAULT '0',
  `provider_name` varchar(100) NOT NULL DEFAULT '',
  `goods_number` smallint(5) unsigned NOT NULL DEFAULT '0',
  `goods_weight` decimal(10,3) unsigned NOT NULL DEFAULT '0.000',
  `market_price` decimal(10,2) unsigned NOT NULL DEFAULT '0.00',
  `shop_price` decimal(10,2) unsigned NOT NULL DEFAULT '0.00',
  `promote_price` decimal(10,2) unsigned NOT NULL DEFAULT '0.00',
  `promote_start_date` int(11) unsigned NOT NULL DEFAULT '0',
  `promote_end_date` int(11) unsigned NOT NULL DEFAULT '0',
  `warn_number` tinyint(3) unsigned NOT NULL DEFAULT '1',
  `keywords` varchar(255) NOT NULL DEFAULT '',
  `goods_brief` varchar(255) NOT NULL DEFAULT '',
  `goods_desc` text NOT NULL,
  `goods_thumb` varchar(255) NOT NULL DEFAULT '',
  `goods_img` varchar(255) NOT NULL DEFAULT '',
  `original_img` varchar(255) NOT NULL DEFAULT '',
  `is_real` tinyint(3) unsigned NOT NULL DEFAULT '1',
  `extension_code` varchar(30) NOT NULL DEFAULT '',
  `is_on_sale` tinyint(1) unsigned NOT NULL DEFAULT '1',
  `is_alone_sale` tinyint(1) unsigned NOT NULL DEFAULT '1',
  `is_shipping` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `integral` int(10) unsigned NOT NULL DEFAULT '0',
  `add_time` int(10) unsigned NOT NULL DEFAULT '0',
  `sort_order` smallint(4) unsigned NOT NULL DEFAULT '100',
  `is_delete` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `is_best` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `is_new` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `is_hot` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `is_promote` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `bonus_type_id` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `share_bonus_type` int(11) DEFAULT '0' COMMENT '分享红包类型id',
  `last_update` int(10) unsigned NOT NULL DEFAULT '0',
  `goods_type` smallint(5) unsigned NOT NULL DEFAULT '0',
  `seller_note` varchar(255) NOT NULL DEFAULT '',
  `give_integral` int(11) NOT NULL DEFAULT '-1',
  `rank_integral` int(11) NOT NULL DEFAULT '-1',
  `suppliers_id` int(5) unsigned DEFAULT '0',
  `is_check` tinyint(1) unsigned DEFAULT '0',
  `team_num` int(11) NOT NULL DEFAULT '5' COMMENT '参团人数',
  `team_price` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '团购价',
  `little_img` varchar(100) DEFAULT NULL COMMENT '小图片',
  `sales_num` int(10) NOT NULL COMMENT '销量',
  `check_desc` varchar(255) DEFAULT NULL,
  `is_mall` tinyint(4) NOT NULL DEFAULT '0' COMMENT '微商城',
  `is_team` tinyint(4) DEFAULT '0' COMMENT '团购',
  `is_zero` tinyint(1) DEFAULT '0' COMMENT '零元购',
  `is_nearby` tinyint(4) NOT NULL DEFAULT '1' COMMENT '附近的团是否开启',
  `use_goods_sn` varchar(30) NOT NULL,
  `guige` varchar(100) NOT NULL,
  `limit_buy_bumber` int(10) NOT NULL DEFAULT '0',
  `limit_buy_one` int(10) NOT NULL DEFAULT '0',
  `city_id` int(10) NOT NULL,
  `province_id` int(10) NOT NULL,
  `district_id` int(10) NOT NULL,
  `subscribe` tinyint(4) NOT NULL DEFAULT '0' COMMENT '关注后购买',
  `shared_allow` tinyint(1) DEFAULT '0' COMMENT '是否允许分成',
  `shared_money` decimal(10,2) DEFAULT '0.00' COMMENT '团员佣金',
  `discount_type` tinyint(1) DEFAULT NULL,
  `discount_amount` decimal(10,2) DEFAULT NULL,
  `bonus_allowed` tinyint(1) DEFAULT '1' COMMENT '是否能使用优惠券',
  `default_shipping_id` smallint(3) DEFAULT '0' COMMENT '指定快递方式',
  `default_shipping_fee` decimal(10,2) DEFAULT NULL COMMENT '默认快递费',
  `default_step_fee` decimal(10,2) DEFAULT NULL COMMENT '每次加价',
  `spe_shipping_fee` decimal(10,2) DEFAULT NULL COMMENT '指定区域快递费',
  `spe_step_fee` decimal(10,2) DEFAULT NULL COMMENT '指定区域每次加价',
  `spe_region` varchar(250) DEFAULT NULL COMMENT '指定区域',
  `express` text COMMENT '配送列表',
  `allow_fenxiao` tinyint(1) DEFAULT '0' COMMENT '是否允许分销',
  `shipping_fee` decimal(10,2) DEFAULT '0.00' COMMENT '邮费',
  `is_tejia` tinyint(1) DEFAULT '0' COMMENT '特价',
  `is_fresh` tinyint(1) DEFAULT '0' COMMENT '新人',
  `is_miao` tinyint(1) DEFAULT '0' COMMENT '秒杀',
  `is_luck` tinyint(1) DEFAULT '0' COMMENT '夺宝',
  `luck_times` int(10) DEFAULT '1' COMMENT '当前期数',
  `max_luck_times` int(10) DEFAULT '1' COMMENT '最大期数',
  `bonus_free_all` int(10) DEFAULT '0' COMMENT '免单券',
  `rate_1` decimal(10,2) DEFAULT '0.00',
  `rate_2` decimal(10,2) DEFAULT '0.00',
  `rate_3` decimal(10,2) DEFAULT '0.00',
  `dbgz` varchar(255) DEFAULT NULL,
  `lab_qgby` varchar(100) NOT NULL,
  `lab_zpbz` varchar(100) NOT NULL,
  `lab_qtth` varchar(100) NOT NULL,
  `lab_jkbs` varchar(100) NOT NULL,
  `lab_hwzy` varchar(100) NOT NULL,
  `ts_a` varchar(100) NOT NULL,
  `ts_b` varchar(100) NOT NULL,
  `ts_c` varchar(100) NOT NULL,
  `allow_sharej` tinyint(1) NOT NULL DEFAULT '0',
  `share_j` int(10) DEFAULT NULL,
  `is_app` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT 'APP专享',
  PRIMARY KEY (`goods_id`),
  KEY `goods_sn` (`goods_sn`),
  KEY `cat_id` (`cat_id`),
  KEY `last_update` (`last_update`),
  KEY `brand_id` (`brand_id`),
  KEY `goods_weight` (`goods_weight`),
  KEY `promote_end_date` (`promote_end_date`),
  KEY `promote_start_date` (`promote_start_date`),
  KEY `goods_number` (`goods_number`),
  KEY `sort_order` (`sort_order`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8");

require("../../inc/footer.php");
?>